# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20160221_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
