# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='knock_url_0',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='knock_url_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='knock_url_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='knock_url_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
