# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20160223_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='knock_postion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
