# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20160223_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='knock_postion',
            new_name='knock_position',
        ),
    ]
