# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20160223_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret_message',
            old_name='srt_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='secret_message',
            old_name='srt_title',
            new_name='title',
        ),
    ]
