# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20160223_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret_message',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
